name: bullshit
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  rxdart: ^0.28.0
  flutter_timezone: ^5.0.1
  intl: ^0.20.2
  flutter_inset_shadow: ^2.0.3
  permission_handler: ^11.3.1
  file_picker: ^8.0.0
  record: ^6.0.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.2
  gal: ^2.3.2
  sensors_plus: ^7.0.0
  android_alarm_manager_plus: ^5.0.0
  android_intent_plus: ^6.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/illusts/
    - assets/images/
    - assets/sounds/
    - assets/logo.png

  fonts:
    - family: HYcysM
      fonts:
        - asset: assets/fonts/HYcysM.ttf
    - family: HYkanB
      fonts:
        - asset: assets/fonts/HYkanB.ttf
    - family: HYkanM
      fonts:
        - asset: assets/fonts/HYkanM.ttf

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png
